[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
addopts = --nomigrations --cov=apps/users --cov=apps/categories --cov=apps/courses --cov=apps/enrollments --cov=apps/progress --cov=apps/reviews --cov=apps/wishlist --cov=apps/dashboard --cov-report=term-missing
